### ISSUE TITLE
Questions about Whitelist, Case Frequency and Account Occupancy

### ISSUE THREAD

**Issue by 45656456kawai** [IceQ1337/OverwatchChecker#10]
Hi, I hope you're having a good day.

I was wondering what's the format for adding multiple whitelist steam id's?
and how often does the bot check for OW cases? as soon they are available or specific time frame?

Also, I wanted to know what happens when one or more assigned accounts start playing csgo in another pc while the bot/script is running? Do they log in automatically once that account is free (not getting used by anyone) or do we have to re-start the script?

Thank you.

**Comment by IceQ1337** [comment]
Hi.

> 
> I was wondering what's the format for adding multiple whitelist steam id's?

The whitelist is stored in an array which contains the steamID64 of one or more profiles.
e.g. `"Whitelist": [ steamID64 , steamID64 , steamID64 , steamID64 ]`

> 
> and how often does the bot check for OW cases? as soon they are available or specific time frame?

The script checks whether a case is available. If this is not the case, it will check again in a little less than a minute, (probably) depending on the accounts overwatch score.

> 
> Also, I wanted to know what happens when one or more assigned accounts start playing csgo in another pc while the bot/script is running? Do they log in automatically once that account is free (not getting used by anyone) or do we have to re-start the script?

I recommend not playing on an account that is currently used by the script. Similar to idling scripts, this can lead to VAC Authentification Errors that will kick you from the current game server. This script does not check whether an account is used somewhere else.
