### ISSUE TITLE
Not able to install V2

### ISSUE THREAD

**Issue by 45656456kawai** [IceQ1337/OverwatchChecker#13]
PS C:\Users\owserver\Desktop\V2> npm install
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\minimist-1d176377\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\debug-75566a04\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\ms-9e6f62bb\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\minimist-1d176377\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\debug-75566a04\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\ms-9e6f62bb\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\minimist-1d176377\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\ms-9e6f62bb\license.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\qs-24caede0\dist\qs.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\minimist-4ad77bb1\example\parse.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\minimist-1d176377\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\ms-9e6f62bb\readme.md'npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\minimist-4ad77bb1\readme.markdown'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\pstree.remy-b1964ebb\tests\fixtures\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\pstree.remy-b1964ebb\tests\fixtures\out1'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\pstree.remy-b1964ebb\tests\fixtures\out2'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\rules\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\utils\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\config\load.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\utils\log.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\utils\merge.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\object-inspect-acc459ed\example\fn.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\cli\parse.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\object-inspect-acc459ed\example\inspect.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\rules\parse.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\monitor\run.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\monitor\signals.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\nodemon-ec7a02ce\lib\monitor\watch.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\AdvanceStringIndex.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\ArrayCreate.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\ArrayCreate.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\ArraySetLength.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\ArraySetLength.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\ArraySpeciesCreate.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\ArraySpeciesCreate.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\Call.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\Call.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\CanonicalNumericIndexString.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CanonicalNumericIndexString.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\5\CheckObjectCoercible.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\CompletePropertyDescriptor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\CompletePropertyDescriptor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\CompletePropertyDescriptor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\CompletePropertyDescriptor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CompletePropertyDescriptor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\CopyDataProperties.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CopyDataProperties.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\CreateDataProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\CreateDataProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\CreateDataProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\CreateDataProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CreateDataProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\CreateDataPropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\CreateDataPropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\CreateDataPropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\CreateDataPropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CreateDataPropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\CreateHTML.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\CreateHTML.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\CreateHTML.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\CreateHTML.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CreateHTML.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\CreateIterResultObject.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\CreateIterResultObject.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\CreateIterResultObject.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\CreateIterResultObject.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CreateIterResultObject.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\CreateListFromArrayLike.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\CreateListFromArrayLike.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\CreateListFromArrayLike.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\CreateListFromArrayLike.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CreateListFromArrayLike.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\CreateMethodProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\CreateMethodProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\CreateMethodProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\CreateMethodProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\CreateMethodProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\DateFromTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\DateFromTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\DateFromTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\DateFromTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\DateFromTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\5\DateFromTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\DateString.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\DateString.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\Day.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\Day.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\Day.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\Day.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\Day.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\5\Day.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\DayFromYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\DayFromYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\DayFromYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\DayFromYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\DayFromYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\5\DayFromYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\DaysInYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\DaysInYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\DaysInYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\DaysInYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\DaysInYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\5\DaysInYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\DayWithinYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\DayWithinYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\DayWithinYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\DayWithinYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\DayWithinYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\5\DayWithinYear.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\DefinePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\DefinePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\DefinePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\DefinePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\DefinePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\DeletePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\DeletePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\DeletePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\DeletePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\DeletePropertyOrThrow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\test\diffOps.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2015\EnumerableOwnNames.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2016\EnumerableOwnNames.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2017\EnumerableOwnProperties.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2018\EnumerableOwnPropertyNames.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\2019\EnumerableOwnPropertyNames.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\es2015.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\test\es2015.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\es2016.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\test\es2016.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\es2017.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\test\es2017.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\es2018.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\test\es2018.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\es2019.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\test\es2019.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\es5.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\owserver\Desktop\V2\node_modules\.staging\es-abstract-b3432d49\test\es5.js'
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/IceQ1337/node-globaloffensive.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\owserver\AppData\Roaming\npm-cache\_logs\2020-01-21T05_17_28_845Z-debug.log

**Comment by IceQ1337** [comment]
It works fine for me on three different machines. Please try again after deleting the node_modules folder. If it still doesn't work, try updating npm to at least version 6.13.4

**Comment by 45656456kawai** [comment]
Still the same errors 

Tried on

 12.14.1 LTS
Recommended For Most Users

and

13.6.0 Current
Latest Features

Tried on 4 systems all windows 10 same error

**Comment by 45656456kawai** [comment]
npm -v
6.13.6

seems to be on latest version

**Comment by IceQ1337** [comment]
Then please delete the `package-lock.json` file and after that, revert [this](https://github.com/IceQ1337/OverwatchChecker/commit/cad6a368db0bf5e56db076334c268da006f4105c) commit.  
In the `package.json` file, change line 28 to: `"globaloffensive": "^2.0.2",`.  

If it still doesn't work, there is no problem with the script itself and I'm actually assuming that because it works just fine for other people. The only problem i can imagine is that you have issues downloading a dependency from my fork at [IceQ1337/node-globaloffensive](https://github.com/IceQ1337/node-globaloffensive).  

However, if it does work, download my fork from the link above and replace the `index.js` and `helpers.js` file within the folder `node_modules/globaloffensive`. Otherwise, the script will crash. If it runs, you are likely to encounter other bugs, but as always, just open another issue and i will try to fix it.

**Comment by 45656456kawai** [comment]
PS C:\Users\owserver\Desktop\OverwatchChecker-master> npm install

> protobufjs@6.8.8 postinstall C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\protobufjs
> node scripts/postinstall


> nodemon@2.0.2 postinstall C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 274 packages from 215 contributors and audited 500 packages in 15.907s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\owserver\Desktop\OverwatchChecker-master>     


change line 28 to: "globaloffensive": "^2.0.2",.

I guess that worked ; )

**Comment by 45656456kawai** [comment]
new error when running "npm index.js"

C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\async.js:49
        fn = function () { throw arg; };
                           ^

Error: StatusCodeError: 404 - {"ok":false,"error_code":404,"description":"Not Found"}
    at C:\Users\owserver\Desktop\V2\node_modules\telegram-bot-api\lib\telegram-bot.js:1746:19
    at tryCatcher (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\owserver\Desktop\V2\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)


after notifying me about the account's username and followed by Logging in to Steam. Than the error

**Comment by 45656456kawai** [comment]
I wonder if there's any way to "npm install" without modifying existing files ... what could be preventing me from downloading the dependency.

Before I never had any problem when doing "npm install"

And it's not just me, unfortunately, I've asked 2 friends to try the same and they have a similar issue.

I myself tried on 3 different systems and also tried with VPN just in case and all came back with the same error. I wonder if you can upload the installed zip file somewhere which doesn't require me doing "npm install" not sure if would work like that :/

**Comment by IceQ1337** [comment]
But you are not using any files from version 1.0 right? I haven't mentioned it anywhere, but the two versions are not compatible with each other.   

> I wonder if you can upload the installed zip file somewhere which doesn't require me doing "npm install" not sure if would work like that :/

Download and try to start this [release](https://github.com/IceQ1337/OverwatchChecker/releases/tag/2.0).   

If that doesn't work. Try reinstalling Node.js completely. The script definitely runs on both Node.js 10 and 12.

**Comment by 45656456kawai** [comment]
Nope, not using any files from the previous version.

with the packed version getting similar error

[Tue, 21 Jan 2020 18:10:04 GMT] STEAM (username) > Logging in to Steam.
Error: [Tue, 21 Jan 2020 18:10:04 GMT] STEAM (csgoftw21) > Error: InvalidPassword
    at module.exports.<anonymous> (C:\Users\owserver\Desktop\V2\modules\steam.js:28:23)
    at SteamUser.emit (events.js:215:7)
    at SteamUser.<anonymous> (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\logon.js:461:9)
    at C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\messages.js:545:24)
    at SteamUser._handleNetMessage (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\messages.js:480:7)
    at SteamUser.processMulti (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\messages.js:572:9)
    at SteamUser.<anonymous> (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\messages.js:566:16)
    at C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\messages.js:545:24)
    at SteamUser._handleNetMessage (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\messages.js:480:7)
    at TCPConnection._readMessage (C:\Users\owserver\Desktop\V2\node_modules\steam-user\components\connection_protocols\tcp.js:193:12)
    at Socket.emit (events.js:210:5)

**Comment by 45656456kawai** [comment]
Not using any old files.

With the packed version getting the same error

[Tue, 21 Jan 2020 18:14:20 GMT] STEAM (username) > Logging in to Steam.
C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\async.js:49
        fn = function () { throw arg; };
                           ^

Error: StatusCodeError: 404 - {"ok":false,"error_code":404,"description":"Not Found"}
    at C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\telegram-bot-api\lib\telegram-bot.js:1746:19
    at tryCatcher (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\owserver\Desktop\OverwatchChecker-master\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
PS C:\Users\owserver\Desktop\OverwatchChecker-master>

**Comment by IceQ1337** [comment]
I don't know for sure, but this error seems to be related to your telegram bot.  Make sure you didn't just copy the old config over, since the new one is a bit different.  

I've made adjustments to the package.json file and was able to install the script in several test environments without any problems. I don't think there is anything to fix on my site.
