### ISSUE TITLE
Script crashing when requesting a second overwatch case

### ISSUE THREAD

**Issue by 45656456kawai** [IceQ1337/OverwatchChecker#14]
[Wed, 22 Jan 2020 02:52:10 GMT] CSGO (steamid64) > Received Confirmation Response. Wating 1 minute.
[Wed, 22 Jan 2020 02:52:10 GMT] CSGO (steamid64) > Received Confirmation Response. Wating 1 minute.
C:\Users\owserver\Desktop\V2\node_modules\globaloffensive\index.js:154
        this._send(Language.PlayerOverwatchCaseUpdate, Protos.CMsgGCCStrike15_v2_PlayerOverwatchCaseUpdate, caseupdate || { reason: 1 });
             ^

TypeError: this._send is not a function
    at Timeout.GlobalOffensive.requestOverwatchCaseUpdate [as _onTimeout] (C:\Users\owserver\Desktop\V2\node_modules\globaloffensive\index.js:154:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
PS C:\Users\owserver\Desktop\V2>

So I fixed the telegram bot token earlier I just copied the old config as it looked similar anyway so that's fixed but I'm still unable to install the latest commit it giving the same error like before on every system I try : /

So i decided to stick with the Packed version and after completing a case the scripts crashing with the error above ^

**Comment by IceQ1337** [comment]
The installation definitely works, unfortunately I don't know what the problem is on your end (it may have something to do with git not being installed), but you can always do the step as described in https://github.com/IceQ1337/OverwatchChecker/issues/13#issuecomment-576721484 which seems to have worked for you.  

However, i was able to confirm the new error and will look at this today.

**Comment by 45656456kawai** [comment]
Yeap git fixed the installation issue : )

**Comment by 45656456kawai** [comment]
Also while you're fixing the current bug I was wondering if it would be possible to tweak the notification message which we get in Telegram.

1. The URL for the demo is always incorrect it's missing "_" sign hence it says Not Found when opening the link
example- 
http://replay189.valve.net/730/002478357460708171965_0925478124.dem.bz2 <-- correct
http://replay189.valve.net/730/0024783574607081719650925478124.dem.bz2 <- telegram

2. Would be so much easier if it can also link the steam profile 
 example-
A monitored account was spotted in an overwatch case on dedust2!
Demo: http://replay189.valve.net/730/0024783574607081719650925478124.dem.bz2
Suspect - https://steamcommunity.com/profiles/76561198053484141

**Comment by IceQ1337** [comment]
>     1. The URL for the demo is always incorrect it's missing "_" sign hence it says Not Found when opening the link
>        example-
>        http://replay189.valve.net/730/002478357460708171965_0925478124.dem.bz2 <-- correct
>        http://replay189.valve.net/730/0024783574607081719650925478124.dem.bz2 <- telegram
> 
>     2. Would be so much easier if it can also link the steam profile
>        example-
>        A monitored account was spotted in an overwatch case on dedust2!
>        Demo: http://replay189.valve.net/730/0024783574607081719650925478124.dem.bz2
>        Suspect - https://steamcommunity.com/profiles/76561198053484141

Thanks, I've made both changes in the development branch. They will be added to the master branch when the other bug is fixed. See https://github.com/IceQ1337/OverwatchChecker/commit/6c2b7a4cb9e06c160c48a046da8b5f8501889b03 and https://github.com/IceQ1337/OverwatchChecker/commit/13202719d7ad6e17cd95fcd9e0f75e530fa27412  

I already know why the other error occurs, but I'm still working on fixing it properly, which could possibly take a few more days.

**Comment by 45656456kawai** [comment]
Awesome bro 👍 

I really appreciate your hard work and dedication, Thank you.
