### ISSUE TITLE
/check command 

### ISSUE THREAD

**Issue by 45656456kawai** [IceQ1337/OverwatchChecker#16]
Hi, I'm using the latest version now and so far there's no crash or error however the /check command doesn't seem to work

I copied steam64id from one of the databases and used /check command for that and the result was  

"This profile is not in our overwatch database."

tried multiple steamid's same results for every /check so it could be a bug since I copied the steam64id's from the database.

Edit: haven't gotten any watchlist notification either so not sure if that's working or not yet. Not sure if it's having issues with checking databases since there's now so many each for every account.

**Comment by 45656456kawai** [comment]
Also what causes "no GC connection"? I'm getting that on only one account

Edit: /watch command doesn't support custom url only steamID64 or else
Invalid Argument.

**Comment by 45656456kawai** [comment]
Alright, now I can confirm that the watchlist also not working. All I could think of is that it's having a problem checking the databases.

**Comment by IceQ1337** [comment]
> Edit: /watch command doesn't support custom url only steamID64 or else
Invalid Argument.   

That is intentional for now. I didn't want to do more asynchronous queries before getting the script to run properly first.

> Alright, now I can confirm that the watchlist also not working. All I could think of is that it's having a problem checking the databases.

That's correct and I'm already looking at it.

**Comment by IceQ1337** [comment]
/check and watchlist notifications should work again now.

> Also what causes "no GC connection"? I'm getting that on only one account 
>
I can't say for sure. It could be due to connection problems/losses, too many requests, etc.  
Also, have you ever started CS:GO manually on this account?

> Edit: /watch command doesn't support custom url only steamID64 or else
> Invalid Argument.
>
As already mentioned, this will be added again in the future.

**Comment by 45656456kawai** [comment]
> /check and watchlist notifications should work again now.
> 
> > Also what causes "no GC connection"? I'm getting that on only one account
> 
> I can't say for sure. It could be due to connection problems/losses, too many requests, etc.
> Also, have you ever started CS:GO manually on this account?
> 
> > Edit: /watch command doesn't support custom url only steamID64 or else
> > Invalid Argument.
> 
> As already mentioned, this will be added again in the future.

Yes, I've started csgo manually on pretty much every account since I have to maintain the rank in order to have overwatch enabled.
