### ISSUE TITLE
 No GC Connection. Retrying indefinitely

### ISSUE THREAD

**Issue by 45656456kawai** [IceQ1337/OverwatchChecker#18]
> [Tue, 28 Jan 2020 23:15:58 GMT] CSGO (steam64id) > Overwatch Cooldown. Retrying in 5 minutes.
[Tue, 28 Jan 2020 23:15:58 GMT] CSGO (steam64id) > Overwatch Cooldown. Retrying in 5 minutes.
[Tue, 28 Jan 2020 23:16:01 GMT] CSGO (steam64id) > Overwatch Cooldown. Retrying in 5 minutes.
[Tue, 28 Jan 2020 23:20:50 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:20:50 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:20:51 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:20:56 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:20:57 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:20:57 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:20:58 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:20:58 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:01 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:20 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:20 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:21 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:26 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:27 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:27 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:28 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:28 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:31 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:45 GMT] STEAM (csgobot1) > Logged in to Steam. Starting CS:GO.
[Tue, 28 Jan 2020 23:21:50 GMT] STEAM (csgobot2) > Logged in to Steam. Starting CS:GO.
[Tue, 28 Jan 2020 23:21:50 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:50 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:51 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:56 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:57 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:57 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:58 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:21:58 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:01 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:03 GMT] STEAM (csgobot3) > Logged in to Steam. Starting CS:GO.
[Tue, 28 Jan 2020 23:22:20 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:20 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:21 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:26 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:27 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:27 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:28 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:28 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:31 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:50 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:50 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:51 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:56 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:57 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:57 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:58 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:22:58 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:01 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:17 GMT] STEAM (zxc) > Logged in to Steam. Starting CS:GO.
[Tue, 28 Jan 2020 23:23:20 GMT] STEAM (zxc) > Logged in to Steam. Starting CS:GO.
[Tue, 28 Jan 2020 23:23:20 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:20 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:21 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:26 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:27 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:27 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:28 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:28 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:31 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:50 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:50 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:51 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:56 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:57 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:57 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:58 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:23:58 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Tue, 28 Jan 2020 23:24:01 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.

Goes on for 5 hours

[Wed, 29 Jan 2020 04:20:37 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:20:37 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:20:41 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:20:59 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:20:59 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:02 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:06 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:06 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:07 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:07 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:07 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:11 GMT] CSGO (null) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:29 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:29 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.
[Wed, 29 Jan 2020 04:21:32 GMT] CSGO (steam64id) > No GC Connection. Retrying in 30 seconds.

I just checked the script and all the accounts were looping NO GC Connection and the last entry to the databases was 6 hours ago. So the script worked fine for about 8 hours

**Comment by 45656456kawai** [comment]
Also, Map name missing from watchlist notification ; )

Overwatch Suspect in Watchlist!
Account: xyz
Suspect: xyz
Demo: xyz
Map: missing

**Comment by IceQ1337** [comment]
I'm really unsure how the GC works sometimes. Does it really say "CSGO (null)" in the logs? If so, I could try to renew the account's steam session if this occurs. Did it work again after restarting the script?

> Also, Map name missing from watchlist notification ; )
> 

Unfortunately, as mentioned in https://github.com/IceQ1337/OverwatchChecker/issues/12#issuecomment-576450948, We no longer have any information about the map that was played. I don't want to make the script more complicated by downloading demos only for this information.

**Comment by 45656456kawai** [comment]
Yes, it says null I only renamed steamid64 and account name. And Yes it works fine for a couple of hours without GC error after restarting the script.

Ahh, that's actually good it saves bandwidth as well. I didn't realize it's not downloading demos anymore.

**Comment by IceQ1337** [comment]
Can you please test if this still occurs with the new version from the [development branch](https://github.com/IceQ1337/OverwatchChecker/tree/development)? I added an event emitter in https://github.com/IceQ1337/OverwatchChecker/commit/6d2b01c0a30834ce9325e80159942c43362bdd67 which tells steam to log in again when the account is disconnected.

**Comment by 45656456kawai** [comment]
Testing

**Comment by 45656456kawai** [comment]
No GC Connection. Retrying in 30 seconds. loop again on 4 accounts so far

**Comment by IceQ1337** [comment]
> No GC Connection. Retrying in 30 seconds. loop again on 4 accounts so far
>
I am unable to prevent this as it is not (directly) caused by my script and I don't know whats causing it. However, in addition to relog after a disconnect, I could try relogging after ~10 failed attempts aswell.  

Have any accounts relogged into steam? If so, did it work again?

**Comment by 45656456kawai** [comment]
Didn't re-log even after an hour (database inactivity) so I re-started the script and so far no GC error yet. It's been an hour or so.

**Comment by 45656456kawai** [comment]
Last night script ran 6 hours fine then-No GC Connection on all of the accounts for ~3 mins after that it started working fine for another 6 hours then again No GC Connection for about 6 mins and then I accidentally closed the script lol : /

**Comment by IceQ1337** [comment]
I think that's a good sign and I'll leave it at that for now.

**Comment by 45656456kawai** [comment]
new result

started script ~3 hours ago and it rank fine for 2 hours and then No GC Connection for about 10 mins and some accounts recovered and started working again then after 20 mins GC error and only a couple of the accounts recovered after 20 mins of GC error and most of the account still looping

**Comment by IceQ1337** [comment]
This could be due to the GC not being available right now. See https://steamstat.us/. However, can you please test the script from the [development branch](https://github.com/IceQ1337/OverwatchChecker/tree/development) again with the changes of https://github.com/IceQ1337/OverwatchChecker/commit/b09d7527c6a2b8241f4f2d2dc570578d9870c791 and https://github.com/IceQ1337/OverwatchChecker/commit/265d4aac559960e58b1140271b27dfd5edff339b if it is available again?   

I have now made it so the accounts will relog in to steam after 10 failed requests (No GC Connection) with them being still connected to steam. Each failed request will exponentially increase the time in which we will try to make a request again (30 seconds * failed_requests). With 9 failed requests being the maximum, the next request will be made after 270 seconds (4,5 minutes) in which we may get connected to the GC again. I may even double the maximum number of failed requests to 20, because we are still connected to steam and we are continuously trying to reconnect to the GC anyway.

**Comment by 45656456kawai** [comment]
Yes, I'll test the latest commits once steam stops dying.

**Comment by 45656456kawai** [comment]
No GC error ran for 10 hours.
