### ISSUE TITLE
No GC Connection.

### ISSUE THREAD

**Issue by 45656456kawai** [IceQ1337/OverwatchChecker#26]
Hello. hope you're doing well.

Lately, I've been getting a lot of GC errors on 7-8 accounts after 10 tries they get offline.

No GC Connection. Failed 10 Times. the last log before going offline.

**Comment by IceQ1337** [comment]
I have no influence on the GC's answers and there is nothing I can do about it.  
After 10 failed attempts, the steam account should log out and then log in again.
