### ISSUE TITLE
Database check

### ISSUE THREAD

**Issue by 45656456kawai** [IceQ1337/OverwatchChecker#7]
Hi, I was wondering if there's any way to check the database every x minutes for listed profiles just like your SteamBanChecker does.
Also would be nice if it exports all the suspects steam profile link to a text file or takes a screenshot of the profile.
Thanks, appreciate your work.

**Comment by IceQ1337** [comment]
> I was wondering if there's any way to check the database every x minutes for listed profiles just like your SteamBanChecker does.

Hi, if I understand correctly, you want to be informed as soon as a case has a certain suspect, right? A better and easier way for this would be to check on each new case instead of checking all cases every x minutes.

I like this suggestion and will implement it soon, if not today.

> Also would be nice if it exports all the suspects steam profile link to a text file or takes a screenshot of the profile.

I will ignore this for the time being because I am currently having problems with screenshots in general, which is why they have been temporarily removed from the [SteamBanChecker](https://github.com/IceQ1337/SteamBanChecker) and the database already contains the SteamID64 of all profiles. You would only have to convert the SteamIDs into links.

**Comment by IceQ1337** [comment]
I added this functionality in https://github.com/IceQ1337/OverwatchChecker/commit/ea87aeea55f9fee97b7a4ecd28b4dee07940b5b7. The bot owner can now monitor accounts by adding them to a list with `/monitor`. At the end of each case, it is checked whether the account is being monitored.

Let me know if this was what you asked for.

**Comment by 45656456kawai** [comment]
Yo, that's exactly what I wanted. I've set up a couple of profiles for monitoring.

Thank you a ton.

**Comment by 45656456kawai** [comment]
It seems that only one profile can be monitored at a time according to monitored.db there's only one profile listed and I added more than 5 or am I doing something wrong here?

**Comment by IceQ1337** [comment]
There was a typo on line 146 in the server.js file (https://github.com/IceQ1337/OverwatchChecker/commit/42cd371816d99430736b47e9b5e3c5628ea5fef8). Please let me know if it works properly now.

To prevent future errors, you may have to adjust the existing entry/entries in the monitored.db file or have the file regenerated. You would have to change all occurrences of "steamid" to "steamid64".

> Before: `{"steamid":"76561198120604750","_id":"XYZ"}`
> After: `{"steamid64":"76561198120604750","_id":"XYZ"}`

**Comment by 45656456kawai** [comment]
Works fine now cheers.

**Comment by 45656456kawai** [comment]
btw this message always comes up but only sometimes it crases cmd randomly anyway to fix that?

(node:2856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
